name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - 'marketing/**'

defaults:
  run:
    working-directory: marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd marketing
          npm install

          - name: Build project
            run: |
              cd marketing
              npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd marketing
          firebase deploy --only hosting:marketing --token ${{ secrets.FIREBASE_TOKEN }}
